### ISSUE TITLE
Feature Request: Cloud SuperNet Tracking

### ISSUE THREAD

**Issue by philip-thomas-paradigm** [tidalmigrations/lightmesh-issues#2]
HI, Currently the cloud connector with Azure only tracks subnets and not the Azure address space that the subnet exists in. For example vNET A has a network of 10.21.0.0/16 and 30 subnets defined as /24's , right now there is no way to know if those /24 belong or are based on the the /16. Please consider adding this feature so we can have a better visual of what our supernet's look like. Thanks, Phil

**Comment by dcolebatch** [comment]
Thank you @ParadigmITOps.

We agree that this is the desired behaviour and have bridged your issue into our roadmap now. Will report back here when we have a timeline for release.

**Comment by deepanshubhalotia** [comment]
We have implemented a fix for this,
Please check my recent email on next steps!

**Comment by philip-thomas-paradigm** [comment]
Testing shortly, as a side note, it does not appear the cloud scanning is happening on a regular basis. I just went to look at the timestamp of the cloud sync with Azure and it's date 5/7, which is the last I clicked the sync button. Maybe I missed something, but I thought that should be on some sort of schedule?

**Comment by deepanshubhalotia** [comment]
Hey Phil,
I ll check that and will get back to you!

Thanks

**Comment by dcolebatch** [comment]
Hi @ParadigmITOps - I'm marking this particular issue as closed, but please re-open it if VNET (supernet) in Azure is still not visible for you.  Thanks again for your feedback.
